export const CategorysData = [
  {
    id: 1,
    name: "Верхняя одежда",
    description: "nome 1",
    image: "",
    parent: 0,
  },
  {
    id: 2,
    name: "Куртки",
    description: "nome 2",
    image: "",
    parent: 0,
  },
];
export const SubcategoryData = [
  {
    id: 1,
    name: "test",
    description: "nome 1",
    image: "",
    parent: 1,
  },
  {
    id: 2,
    name: "test",
    description: "nome 1",
    image: "",
    parent: 1,
  },
  {
    id: 3,
    name: "test",
    description: "nome 1",
    image: "",
    parent: 1,
  },
  // {
  //   id: 2,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 2,
  // },
  // {
  //   id: 1,
  //   name: "Куртки",
  //   description: "nome 1",
  //   image: "",
  //   parent: 3,
  // },
  // {
  //   id: 2,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 3,
  // },
  // {
  //   id: 3,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 3,
  // },
  // {
  //   id: 4,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 3,
  // },
  // {
  //   id: 5,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 3,
  // },
  // {
  //   id: 1,
  //   name: "Куртки",
  //   description: "nome 1",
  //   image: "",
  //   parent: 4,
  // },
  // {
  //   id: 2,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 4,
  // },
  // {
  //   id: 3,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 4,
  // },
  // {
  //   id: 4,
  //   name: "Верхняя одежда",
  //   description: "nome 1",
  //   image: "",
  //   parent: 4,
  // },
];
